[project]
name = "automationexercise"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pyyaml>=6.0.2",
    "robotframework==6.1.1",
    "robotframework-faker>=6.0.0",
    "robotframework-seleniumlibrary>=6.7.1",
]
